import '../styles/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import StyledComponentsRegistry from '@/app/registry'
import ContainerContent from '@/components/container/containerContent'
import ContainerBody from '@/components/container/containerBody'
import { ThemeProviderMode } from '@/context/ThemeContext'
import { ThemeProvider } from 'styled-components'
import { Providers } from '@/redux/provider'
import AuthProvider from '@/components/authProvider/authProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          <Providers>
            <ThemeProviderMode>
              <AuthProvider>
                <ContainerBody>
                  <Navbar />
                  {children}
                  <Footer />
                </ContainerBody>
              </AuthProvider>
            </ThemeProviderMode>
          </Providers>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
